In [1]:
import numpy as np

In [2]:
# Tạo numpy array 1 chiều
arr1 = np.array([3, 4, 7, 8, 1, 2, 3])
print(type(arr1))
print(arr1)

In [39]:
# Tạo numpy array 2 chiều
arr2 = np.array(
    [
        [5, 12, 17, 9, 3],
        [13, 4, 8, 14, 1],
        [9, 6, 3, 7, 21],
    ]
)
arr2

dtype('int8')

In [8]:
# Tạo ma trận chỉ chứa các phần tử 0
arr3 = np.zeros((5, 5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# Taoj array chỉ chứa các phần tử 1
arr4 = np.ones((4, 4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# Tạo array chỉ chưa các phần tử bằng nhau
arr5 = np.full((4, 3), 9)
arr5

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [11]:
# Tạo ma trận đơn vị
arr6 = np.eye(7)
arr6

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [25]:
arr7 = np.random.random((2, 3))
arr7

array([[0.34429911, 0.95993683, 0.02199442],
       [0.68324336, 0.88944171, 0.38784597]])

In [26]:
arr8 = np.arange(7)
arr8

array([0, 1, 2, 3, 4, 5, 6])

In [28]:
arr7.shape

(2, 3)

In [29]:
arr7.dtype

dtype('float64')

In [34]:
# Thay đổi kích thước của mảng
my_arr = np.array(
    [
        [5, 12, 17, 9],
        [13, 4, 8, 14],
        [9, 6, 3, 7],
    ]
)
my_arr.reshape(6, 2)

array([[ 5, 12],
       [17,  9],
       [13,  4],
       [ 8, 14],
       [ 9,  6],
       [ 3,  7]])

In [36]:
# Thay đổi kiểu dữ liệu của các phần tử trong mảng
arr7 = arr7.astype(np.float16)
arr7.dtype

dtype('float16')

In [41]:
# Gán kiểu dữ liệu ngay khi khởi tạo
arr8 = np.array(
    [
        [5, 12, 17, 9, 3],
        [13, 4, 8, 14, 1],
        [9, 6, 3, 7, 21],
    ],
    dtype=np.int8,
)
arr8.dtype

dtype('int8')

In [47]:
# Truy cập phần tử trong array
arr9 = np.array([1, 2, 3, 4, 5, 6])
arr10 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
arr10[1, 0]

array([4, 5, 6])

In [54]:
# cộng, trừ, nhân, chia 2 ma trận, bình phương ma trận

matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])
print(matrix_1)
print(matrix_2)

sum_matrix = np.add(matrix_1, matrix_2)
sub_matrix = np.subtract(matrix_1, matrix_2)
mul_matrix = np.multiply(matrix_1, matrix_2)

print(sum_matrix)
print(sub_matrix)
print(mul_matrix)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [61]:
np.savetxt("mul_matrix.txt", mul_matrix)
loaded_arr = np.loadtxt("mul_matrix.txt")
loaded_arr

array([[ 5., 12.],
       [21., 32.]])